Allow for a single device to be used.
michaelphilip/SmartThings pull request #1
Opened 2018-06-14 00:19 UTC by BadPirate

Allows for a single device to be used, issue is deviceIdNames is a String if one is present, and an array if multiple are present (Ughh..) fix is to detect string and wrap it in array.

2018-06-14 02:21 UTC, michaelphilip requested changes
Could you try reverting line 57 and make sure it still works for you (so far as it does, anyway), and then I'll merge your array-wrapping and test it here?  (Like I said in the community, it shouldn't be needed...but shouldn't hurt?)

2018-06-14 23:20 UTC, BadPirate commented
Line 57 is strictly not necessary (just a test that snuck through into the pick) -- But worth having anyway AFAIK.  The array wrapping is the meat of the fix that works for me.

2025-06-05 15:59 UTC, BadPirate commented on smartapps/mpk/leviton-vrcz4-m0z-switch-mapper.src/leviton-vrcz4-m0z-switch-mapper.groovy
> +      def deviceids = (devices.deviceNetworkId instanceof String) ? [devices.deviceNetworkId] : devices.deviceNetworkId
```suggestion
    	def devices = settings['switches_'+it]
      def deviceids = (devices.deviceNetworkId instanceof String) ? [devices.deviceNetworkId] : devices.deviceNetworkId
```

2025-06-05 16:00 UTC, BadPirate commented on smartapps/mpk/leviton-vrcz4-m0z-switch-mapper.src/leviton-vrcz4-m0z-switch-mapper.groovy
> +      def deviceids = (devices.deviceNetworkId instanceof String) ? [devices.deviceNetworkId] : devices.deviceNetworkId
```suggestion
        def devices = settings['switches_'+it]
        def deviceids = (devices.deviceNetworkId instanceof String) ? [devices.deviceNetworkId] : devices.deviceNetworkId
```

2025-06-05 23:14 UTC, merged